var Ext={};Ext.inherits=function(childCtor,parentCtor){function tempCtor(){}tempCtor.prototype=parentCtor.prototype;childCtor.prototype=new tempCtor;childCtor.prototype.constructor=childCtor;childCtor["base"]=function(me,methodName,var_args){if(!methodName)methodName="constructor";var len=arguments.length;var args=new Array(len);for(var i=2;i<len;i++)args[i-2]=arguments[i];return parentCtor.prototype[methodName].apply(me,args)}};window["Ext"]=Ext;Ext["inherits"]=Ext.inherits;var Ary={};Ary.from=function(val){if(val!=null){var len=val.length;if(len>0){var ary=new Array(len);for(var i=0;i<len;++i)ary[i]=val[i];return ary}else return[]}else return[]};Ary.fromProperty=function(objs,prop){var len=objs.length;var ary=new Array(len);for(var i=0;i<len;++i)ary[i]=objs[i][prop];return ary};Ary.is2DArray=function(val){if(Array.isArray(val))for(var i=val.length;--i>=0;)if(Array.isArray(val[i]))return true;return false};
Ary.create2DArray=function(firstD,secondD,defaultVal){var ary=new Array(firstD);for(var i=0;i<firstD;++i)ary[i]=Ary.create(secondD,defaultVal);return ary};Ary.create=function(count,defaultVal,ctx){if(!count)return[];var i,ary=new Array(count);if(defaultVal!==undefined)if(typeof defaultVal==="function")if(ctx!=null)for(i=0;i<count;++i)ary[i]=defaultVal(ctx,i);else for(i=0;i<count;++i)ary[i]=defaultVal(i,i);else for(i=0;i<count;++i)ary[i]=defaultVal;return ary};
Ary.createIndices=function(count,opt_stepVal,opt_startVal){if(!count)return[];var stepVal=opt_stepVal==null?1:opt_stepVal;var ary=new Array(count);ary[0]=opt_startVal||0;for(var i=1;i<count;++i)ary[i]=ary[i-1]+stepVal;return ary};Ary.createSum=function(count,opt_stepVal,opt_startVal){if(!count)return[];var stepVal=opt_stepVal==null?1:opt_stepVal;var ary=new Array(count);ary[0]=opt_startVal||0;var sum=stepVal;for(var i=1;i<count;++i){ary[i]=ary[i-1]+sum;sum+=stepVal}return ary};
Ary.toNumbers=function(str){var values=str.match(/-?[0-9.]+/g);for(var i=values.length;--i>=0;)values[i]=+values[i];return values};Ary.arrayToDict=function(ary,values,outDict){var dict=outDict||{};var i,val;var len=ary.length;if(values===undefined)for(i=0;i<len;++i){var key=ary[i];if(dict[key])++dict[key];else dict[key]=1}else if(Array.isArray(values))for(i=0;i<len;++i)dict[ary[i]]=values[i];else for(i=0;i<len;++i)dict[ary[i]]=values;return dict};
Ary.dictToArray=function(dict,outVals,outKeys){if(!dict)return null;var i,len,keys=Object.keys(dict);if(outKeys){if(outVals)for(i=0,len=keys.length;i<len;++i){var key=keys[i];outKeys.push(key);outVals.push(dict[key])}}else{outKeys=keys;if(outVals)for(i=0,len=keys.length;i<len;++i)outVals.push(dict[keys[i]])}return outKeys};
Ary.toTable=function(str,opt_vSplitter,opt_hSplitter){var strs="";if(opt_vSplitter!=null)strs=str.split(opt_vSplitter);else strs=str.replace(/\]\s*,\s*/g,",\n").replace(/\[|\]|"/g,"").split(/[\r\n]+\W*/g);if(opt_hSplitter==null)opt_hSplitter=new RegExp(", |,|\\t+|\\W{2,}","g");var rowCount=strs.length;var rows=new Array(rowCount);for(var i=0;i<rowCount;++i)rows[i]=strs[i].split(opt_hSplitter);return rows};
Ary.tableToString=function(ary2D,opt_vSeparator,opt_hSeparator){if(opt_vSeparator==null)opt_vSeparator="\n";if(opt_hSeparator==null)opt_hSeparator="\t";var rowCount=ary2D.length;var rows=new Array(rowCount);for(var i=0;i<rowCount;++i)rows[i]=ary2D[i].join(opt_hSeparator);return rows.join(opt_vSeparator)};
Ary.columnToTable=function(ary2D,opt_rowCount){var colCount=ary2D.length;if(colCount<=0)return null;var rowCount=opt_rowCount>0?opt_rowCount:ary2D[0].length;var rows=new Array(rowCount);for(var r=0;r<rowCount;++r){var row=new Array(colCount);rows[r]=row;for(var c=0;c<colCount;++c)row[c]=ary2D[c][r]}return rows};Ary.sortNumbers=function(nums,sortOrder){var order=Ary.getSortOrder(sortOrder);if(order===0)return nums;return nums.sort(order>0?Ary._compareNumberAsc:Ary._compareNumberDsc)};
Ary.sort=function(ary,sortOrder,opt_cmp){var order=Ary.getSortOrder(sortOrder);if(order===0)return ary;if(opt_cmp==null)return ary.sort(order>0?Ary._compareAsc:Ary._compareDsc);return ary.sort(function(a,b){return opt_cmp(a,b,order)})};Ary.getSortOrder=function(sortOrder){if(sortOrder)if(typeof sortOrder==="string"){var strOrder=sortOrder.charAt(0).toLowerCase();if(strOrder==="a")return 1;else if(strOrder==="d")return-1;else return 0}else return+sortOrder;return sortOrder==null?1:0};
Ary.compareObject=function(a,b,order){if(a<b)return-order;if(b<a)return order;return 0};Ary.compareUserData=function(a,b,order){if(a==null||a!==a){if(b==null||b!==b)return 0;return 1}if(b==null||b!==b)return-1;if(a<b)return-order;if(b<a)return order;return 0};Ary._compareAsc=function(a,b){if(a<b)return-1;if(b<a)return 1;return 0};Ary._compareDsc=function(a,b){if(a<b)return 1;if(b<a)return-1;return 0};Ary._compareNumberAsc=function(a,b){return a-b};Ary._compareNumberDsc=function(a,b){return b-a};
Ary.equals=function(ary1,ary2){if(!ary1||!ary2)return false;var len=ary1.length;if(len!=ary2.length)return false;for(var i=0;i<len;++i)if(ary1[i]!==ary2[i])return false;return true};Ary.indexOf=function(ary,item,opt_startAt){if(opt_startAt==null)opt_startAt=0;var len=ary.length;for(var i=opt_startAt;i<len;++i)if(ary[i]===item)return i;return-1};Ary.lastIndexOf=function(ary,item){for(var i=ary.length;--i>=0;)if(ary[i]===item)return i;return-1};
Ary.forEach=function(ary,func,ctxA,ctxB){var len=func&&ary?ary.length:0;if(len){if(ctxA==null)ctxA=ary;for(var i=0;i<len;++i)func(ary[i],i,ctxA,ctxB)}};Ary.map=function(ary,func,ctxA,ctxB){var len=func&&ary?ary.length:0;var out=len?new Array(len):[];if(ctxA==null)ctxA=ary;for(var i=0;i<len;++i)out[i]=func(ary[i],i,ctxA,ctxB);return out};
Ary.moveItem=function(ary,from,to){var len=ary.length;if(from<0||from>=len||from===to)return ary;if(!(to>=0))to=0;var item=ary.splice(from,1)[0];if(to>=len-1)ary.push(item);else ary.splice(to,0,item);return ary};Ary.moveToTop=function(ary,index){if(index>0&&index<ary.length)return ary.concat(ary.splice(index,ary.length-index));return ary};
Ary.moveItems=function(ary,indices,to){var aryLen=ary?ary.length:0;if(!aryLen)return[];var out=ary.slice();var items=[];var len=indices?indices.length:0;for(var i=0;i<len;++i){var idx=indices[i];var val=out[idx];if(val!==undefined){items.push(val);out[idx]=undefined}}if(items.length){Ary.insertItems(out,to,items);out=out.filter(Ary.notUndefined)}return out};Ary.insertItems=function(ary,at,items){if(!at||at<0)at=0;if(items&&items.length)ary.splice.apply(ary,[at,0].concat(items));return ary};
Ary.concatArrays=function(ary,aryOfAry){return ary.concat.apply(ary,aryOfAry)};Ary.push=function(ary,items){if(items){var len=items.length;if(len)if(len>1)Array.prototype.push.apply(ary,items);else ary.push(items[0])}return ary};Ary.insertUniqueItem=function(ary,item,opt_at){var at=Ary.indexOf(ary,item);if(at>=0){if(at===opt_at||opt_at==null)return at;ary.splice(at,1)}if(opt_at==null||opt_at>=ary.length){at=ary.length;ary.push(item);return at}ary.splice(opt_at,0,item);return opt_at};
Ary.removeEmptyItems=function(ary){return ary?ary.filter(Ary.notEmpty):[]};Ary.notNaN=function(num){return num===num};Ary.notUndefined=function(val){return val!==undefined};Ary.notNull=function(val){return val!=null};Ary.notEmpty=function(val){return val?true:val===0};Ary.lessComparator=function(a,b){return a<b};
Ary.lowerBound=function(sortedAry,value,opt_lessFunc,left,right){if(left==null||left<0)left=0;if(right==null||right<0||right>sortedAry.length)right=sortedAry.length;if(left>right)left=right;if(!opt_lessFunc)opt_lessFunc=Ary.lessComparator;while(right>left){var mid=left+right>>1;if(opt_lessFunc(sortedAry[mid],value))left=mid+1;else right=mid}return left};
Ary.upperBound=function(sortedAry,value,opt_lessFunc,left,right){var at=Ary.lowerBound(sortedAry,value,opt_lessFunc,left,right);var matchedVal=sortedAry[at];while(matchedVal===value)++at;return at};Ary.getPercentileFromIndex=function(sortedAry,index){return 100*(index+.5)/sortedAry.length};
Ary.getPercentile=function(sortedAry,value,opt_lessFunc){var index=Ary.lowerBound(sortedAry,value,opt_lessFunc);var matchedVal=sortedAry[index];if(matchedVal!==value){if(index>=sortedAry.length)return 100;if(index<=0)return 0;index--;if(typeof value=="number"){var prevVal=sortedAry[index];index+=(value-prevVal)/(matchedVal-prevVal)}}return Ary.getPercentileFromIndex(sortedAry,index)};
Ary.getIndexFromPercentile=function(ary,pct){var i=ary.length*pct/100-.5;var k=Math.floor(i);var f=i-k;if(f<=1E-6)return k;if(f>=.999999)return k+1;return i};Ary.getValueFromPercentile=function(sortedAry,pct){var i=Ary.getIndexFromPercentile(sortedAry,pct);var k=Math.floor(i);var f=i-k;if(f<=1E-6)f=0;if(f>=.999999)f=1;if(k>=sortedAry.length-1)return sortedAry[sortedAry.length-1];if(k<0)return sortedAry[0];var val=sortedAry[k];var nextVal=sortedAry[k+1];return val+(nextVal-val)*f};
Ary.offset=function(nums,val){for(var i=nums.length;--i>=0;)nums[i]+=val;return nums};Ary.scale=function(nums,mult,opt_mid){if(!opt_mid)opt_mid=0;--mult;for(var i=nums.length;--i>=0;)nums[i]+=(nums[i]-opt_mid)*mult;return nums};Ary.round=function(nums,step){if(step==null)step=100;var rnd=Math.round;for(var i=nums.length;--i>=0;)nums[i]=rnd(nums[i]*step)/step;return nums};Ary.addClass=function(ary,classStr){for(var i=ary.length;--i>=0;)ary[i]["classList"]["add"](classStr)};window["Ary"]=Ary;
(function(){var obj={"from":Ary.from,"fromProperty":Ary.fromProperty,"is2DArray":Ary.is2DArray,"create2DArray":Ary.create2DArray,"create":Ary.create,"createIndices":Ary.createIndices,"createSum":Ary.createSum,"toNumbers":Ary.toNumbers,"arrayToDict":Ary.arrayToDict,"dictToArray":Ary.dictToArray,"toTable":Ary.toTable,"tableToString":Ary.tableToString,"columnToTable":Ary.columnToTable,"sortNumbers":Ary.sortNumbers,"sort":Ary.sort,"getSortOrder":Ary.getSortOrder,"compareObject":Ary.compareObject,"compareUserData":Ary.compareUserData,
"equals":Ary.equals,"indexOf":Ary.indexOf,"lastIndexOf":Ary.lastIndexOf,"forEach":Ary.forEach,"map":Ary.map,"moveItem":Ary.moveItem,"moveToTop":Ary.moveToTop,"moveItems":Ary.moveItems,"insertItems":Ary.insertItems,"concatArrays":Ary.concatArrays,"push":Ary.push,"insertUniqueItem":Ary.insertUniqueItem,"removeEmptyItems":Ary.removeEmptyItems,"notNaN":Ary.notNaN,"notUndefined":Ary.notUndefined,"notNull":Ary.notNull,"notEmpty":Ary.notEmpty,"lessComparator":Ary.lessComparator,"lowerBound":Ary.lowerBound,
"upperBound":Ary.upperBound,"getPercentileFromIndex":Ary.getPercentileFromIndex,"getPercentile":Ary.getPercentile,"getIndexFromPercentile":Ary.getIndexFromPercentile,"getValueFromPercentile":Ary.getValueFromPercentile,"offset":Ary.offset,"scale":Ary.scale,"round":Ary.round,"addClass":Ary.addClass};for(var key in obj)Ary[key]=obj[key]})();var EventDispatcher=function(){};EventDispatcher.prototype._events=null;EventDispatcher.prototype.listen=function(type,listener){this._listen(type,listener,false)};EventDispatcher.prototype.addHighPriorityListener=function(type,listener){this._listen(type,listener,true)};
EventDispatcher.prototype._listen=function(type,listener,priority){if(!this._events)this._events={};var evt=this._events[type];if(!evt){evt={listeners:[]};this._events[type]=evt}var listeners=evt.listeners;if(listeners.indexOf(listener)<0)if(priority)listeners.unshift(listener);else listeners.push(listener)};
EventDispatcher.prototype.unlisten=function(type,listener){if(!this._events)return;var evt=this._events[type];if(evt){var listeners=evt.listeners;var foundAt=listeners.indexOf(listener);if(foundAt>=0)listeners.splice(foundAt,1)}};EventDispatcher.prototype.unlistenAll=function(opt_type){if(!this._events)return;if(opt_type){var evt=this._events[opt_type];if(evt)evt.listeners.length=0}else this._events={}};
EventDispatcher.prototype.addListener=function(type,listeners){var listener=listeners[type];if(typeof listener==="function")this.listen(type,listener)};EventDispatcher.prototype.addListeners=function(listeners){for(var type in listeners)this.addListener(type,listeners)};EventDispatcher.prototype.getListenerCount=function(type){if(!this._events)return 0;var evt=this._events[type];return evt?evt.listeners.length:0};
EventDispatcher.prototype.hasListener=function(type){if(!this._events)return false;var evt=this._events[type];return evt?evt.listeners.length>0:false};EventDispatcher.prototype.dispatch=function(type,eventArg){if(!this._events)return;var evt=this._events[type];if(!evt)return;evt.dispatching=true;if(eventArg)eventArg["sender"]=this;var listeners=evt.listeners;var listCount=listeners.length;for(var i=0;i<listCount;++i)listeners[i](eventArg);evt.dispatching=false};
EventDispatcher.prototype.isDispatching=function(type){if(!this._events)return false;var evt=this._events[type];return evt?evt.dispatching===true:false};EventDispatcher.preventDefault=function(e){e.preventDefault();e.stopPropagation()};window["EventDispatcher"]=EventDispatcher;EventDispatcher["preventDefault"]=EventDispatcher.preventDefault;EventDispatcher._proto=EventDispatcher.prototype;EventDispatcher._proto["listen"]=EventDispatcher._proto.listen;EventDispatcher._proto["unlisten"]=EventDispatcher._proto.unlisten;
EventDispatcher._proto["unlistenAll"]=EventDispatcher._proto.unlistenAll;EventDispatcher._proto["addListener"]=EventDispatcher._proto.addListener;EventDispatcher._proto["addListeners"]=EventDispatcher._proto.addListeners;EventDispatcher._proto["addHighPriorityListener"]=EventDispatcher._proto.addHighPriorityListener;EventDispatcher._proto["getListenerCount"]=EventDispatcher._proto.getListenerCount;EventDispatcher._proto["hasListener"]=EventDispatcher._proto.hasListener;
EventDispatcher._proto["dispatch"]=EventDispatcher._proto.dispatch;EventDispatcher._proto["isDispatching"]=EventDispatcher._proto.isDispatching;var PosUt={};PosUt.getClientPosition=function(target,obj){var pos=obj||{"x":0,"y":0};if(target["getBoundingClientRect"]){var box=target["getBoundingClientRect"]();pos["x"]=box.left;pos["y"]=box.top}else{pos["x"]=target.clientX;pos["y"]=target.clientY}return pos};PosUt.getRelativePosition=function(A,B,obj){obj=PosUt.getClientPosition(A,obj);var bp=PosUt.getClientPosition(B);obj["x"]-=bp["x"];obj["y"]-=bp["y"];return obj};
PosUt.getImmediateChild=function(parent,ref){if(ref){var n=ref.target||ref;if(parent.contains(n)){var child=null;while(n!==parent){child=n;n=n.parentNode}return child}}return null};PosUt.getImmediateChildIndex=function(parent,ref){var n=PosUt.getImmediateChild(parent,ref);if(n){var chdr=parent.children;for(var i=chdr.length;--i>=0;)if(chdr[i]===n)return i}return-1};
PosUt.getClientPositionPt=function(target,ary){var pos=ary||[0,0];if(target["getBoundingClientRect"]){var box=target["getBoundingClientRect"]();pos[0]=box.left;pos[1]=box.top}else{pos[0]=target.clientX;pos[1]=target.clientY}return pos};PosUt.getRelativePositionPt=function(A,B,ary){ary=PosUt.getClientPositionPt(A,ary);var bp=PosUt.getClientPositionPt(B);ary[0]-=bp[0];ary[1]-=bp[1];return ary};
PosUt.closestElement=function(elem,classStr){var n=elem;while(n&&n.classList){if(n.classList.contains(classStr))return n;n=n.parentNode}return null};PosUt.closestTagName=function(elem,tn){var n=elem;while(n&&n.tagName){if(n.tagName==tn)return n;n=n.parentNode}return null};window["PosUt"]=PosUt;
(function(){var obj={"getClientPosition":PosUt.getClientPosition,"getRelativePosition":PosUt.getRelativePosition,"getClientPositionPt":PosUt.getClientPositionPt,"getRelativePositionPt":PosUt.getRelativePositionPt,"getImmediateChild":PosUt.getImmediateChild,"getImmediateChildIndex":PosUt.getImmediateChildIndex,"closestElement":PosUt.closestElement,"closestTagName":PosUt.closestTagName};for(var key in obj)PosUt[key]=obj[key]})();var Listeners;var Dom={};Dom.map=function(elems,names,objMap){if(!objMap)objMap={};if(!elems)return objMap;var list=elems.length?elems:elems.children;var len=list.length||0;for(var i=0;i<len;++i){var n=names[i];if(!n)break;objMap[n]=list[i]}return objMap};
Dom.mapByAttribute=function(elem,attr,objMap){if(!objMap)objMap={};if(!elem)return objMap;if(!attr)attr="id";var descendants=Dom.flatten(elem);var len=descendants.length;for(var i=0;i<len;++i){var el=descendants[i];var attrVal=el.getAttribute(attr);if(attrVal)objMap[attrVal]=el}return objMap};
Dom.getElementsByAttr=function(elem,attr,attrVal,ary){if(!ary)ary=[];var descendants=Array.isArray(elem)?elem:Dom.flatten(elem);var el,i,len=descendants.length;if(attrVal)for(i=0;i<len;++i){el=descendants[i];if(el.getAttribute(attr)===attrVal)ary.push(el)}else for(i=0;i<len;++i){el=descendants[i];if(el.hasAttribute(attr))ary.push(el)}return ary};
Dom.flatten=function(elem,ary){if(!ary)ary=[];if(!elem)return ary;var i=ary.length;var len=i+1;ary.push(elem);while(i<len){var chdr=ary[i].children;var chdrCount=chdr.length;if(chdrCount){for(var j=0;j<chdrCount;++j)ary.push(chdr[j]);len+=chdrCount}++i}return ary};
Dom.firstMatch=function(elem,func,ctx){if(!elem||!func)return[];var ary=[elem];var out_ary=[];var idx=0;if(func(elem,idx++,ctx))out_ary.push(elem);var i=0;var len=1;while(i<len){var chdr=ary[i].children;var chdrCount=chdr.length;for(var j=0;j<chdrCount;++j){var ch=chdr[j];if(func(ch,idx++,ctx))out_ary.push(ch);else{ary.push(ch);++len}}++i}return out_ary};
Dom.rebindEvents=function(elems,eventName,funcMap){var len=elems.length;var attrName="on"+eventName.toLowerCase();for(var i=0;i<len;++i){var elem=elems[i];var funcAttr=elem.getAttribute(attrName);if(funcAttr){var funcAry=funcAttr.match(/\w+/);if(funcAry){var funcName=funcAry[0];var func=funcMap[funcName];if(typeof func==="function"){if(!func.name.match(/^bound /))func=func.bind(funcMap);elem.removeAttribute(attrName);elem.addEventListener(eventName,func)}else console.log(funcName+" does not exist")}}}};
Dom.setPxProp=function(prop,elem,px){if(px!=null){var str=Dom.cssSize(px);if(elem.style[prop]!=str){elem.style[prop]=str;return 1}}return 0};Dom.setWidth=function(elem,opt_width){return Dom.setPxProp("width",elem,opt_width)};Dom.setHeight=function(elem,opt_height){return Dom.setPxProp("height",elem,opt_height)};Dom.cssSize=function(px){if(typeof px=="number")return px?px+"px":"0";if(px)return typeof px=="string"?px:px+"";return""};
Dom.appendChild=function(parentElem,children){if(!parentElem)return null;var i=0;var ary=null;if(Array.isArray(arguments[1]))ary=arguments[1];else if(children){ary=arguments;i=1}var len=ary?ary.length:0;while(i<len){parentElem.appendChild(ary[i]);++i}return parentElem};
Dom.tree=function(parentElem,children){if(parentElem){var args=arguments;var len=args.length;for(var i=1;i<len;++i){var child=args[i];if(child){var childElem=null;if(Array.isArray(child))childElem=Dom.tree.apply(null,child);else if(child.nodeType===1)childElem=child;if(childElem)parentElem.appendChild(childElem)}}}return null};Dom.removeParent=function(elem){if(!elem)return null;var parent=elem.parentNode;if(parent)parent.removeChild(elem);return parent};
Dom.removeChildren=function(elem,count){if(elem){var childCount=elem.childNodes.length;if(count==null||count>childCount)count=childCount;while(--count>=0)elem.removeChild(elem.lastChild)}};Dom.removeNonChildElement=function(elem){if(elem){var nodes=elem.childNodes;var len=nodes?nodes.length:0;var chdr=elem.children;var chdrLen=chdr?chdr.length:0;if(len!==chdrLen)while(--len>=0)if(nodes[len].nodeType!==1)elem.removeChild(nodes[len])}};
Dom.removeTextNodes=function(elem){if(elem){var nodes=elem.childNodes;var len=nodes?nodes.length:0;var chdr=elem.children;var chdrLen=chdr?chdr.length:0;if(len!==chdrLen)while(--len>=0)if(nodes[len].nodeType===3)elem.removeChild(nodes[len])}};Dom.replace=function(oldNode,newNode){if(!newNode){Dom.removeParent(oldNode);return}var pn=oldNode.parentNode;if(pn)pn.replaceChild(newNode,oldNode)};
Dom.setContent=function(elem,val){if(elem)if(val||val===0){var nt=val.nodeType;if(nt===1||nt===3){if(val!==elem.lastChild){Dom.removeChildren(elem);elem.appendChild(val)}}else if(Array.isArray(val)){Dom.removeChildren(elem);Dom.appendChild(elem,val)}else elem.textContent=val}else Dom.removeChildren(elem)};Dom.addClass=function(elem,str){elem.classList.add(str)};
Dom.addEffectClass=function(elem,str,ms){if(elem&&str)if(ms||elem.classList.contains(str)){elem.classList.remove(str);setTimeout(Dom.addClass.bind(null,elem,str),ms||50)}else Dom.addClass(elem,str)};Dom.setTimeoutClass=function(elem,str,ms){Dom.removeTimeoutClass(elem,str);Dom.addTimeoutClass(elem,str,ms)};
Dom.addTimeoutClass=function(elem,str,ms){if(elem&&str){if(elem._clsTimer){if(elem._clsTimer[str])return}else elem._clsTimer={};Dom.addClass(elem,str);elem._clsTimer[str]=setTimeout(Dom._onTimeoutClass.bind(null,elem,str),ms)}};Dom._onTimeoutClass=function(elem,str){elem._clsTimer[str]=0;elem.classList.remove(str)};Dom.removeTimeoutClass=function(elem,str){if(elem&&elem._clsTimer)if(elem._clsTimer[str]){clearTimeout(elem._clsTimer[str]);Dom._onTimeoutClass(elem,str)}};Dom.tag=function(tagName){return document.createElement(tagName)};
Dom.create=Dom.tag;Dom.div=function(){return Dom.tag("div")};Dom.block=function(opt_class,tagName){var div=Dom.tag(tagName||"div");if(opt_class)div.className=opt_class;return div};Dom.icon=function(iconRef,classStr){var elem;if(typeof iconRef=="string"){elem=Dom.div();elem.style.display="inline-block";classStr=iconRef}else elem=iconRef||Dom.div();Dom.addClass(elem,"char");if(classStr)Dom.addClass(elem,classStr);return elem};
Dom.toggleAttribute=function(elem,attr,bool){if(bool)elem.setAttribute(attr,typeof bool==="string"?bool:"");else if(bool==null)if(elem.hasAttribute(attr))elem.removeAttribute(attr);else elem.setAttribute(attr,"");else elem.removeAttribute(attr)};Dom.toggleClass=function(elem,classStr,bool){if(bool)Dom.addClass(elem,classStr);else if(bool==null)if(elem.classList.contains(classStr))elem.classList.remove(classStr);else Dom.addClass(elem,classStr);else elem.classList.remove(classStr)};
Dom.transferAttribute=function(attr,srcElem,destElem,fallback){var str;if(srcElem){str=srcElem.getAttribute(attr);if(str)srcElem.removeAttribute(attr)}if(!str)str=fallback;if(str)destElem.setAttribute(attr,str)};Dom.addClasses=function(elem,classes){if(elem){var ary=Array.isArray(classes)?classes:arguments;var len=ary.length;for(var i=0;i<len;++i){var str=ary[i];if(str&&typeof str=="string")elem.classList.add(str)}}};
Dom.removeClasses=function(elem,classes){if(elem){var ary=Array.isArray(classes)?classes:arguments;var len=ary.length;for(var i=0;i<len;++i){var str=ary[i];if(str&&typeof str=="string")elem.classList.remove(str)}}};Dom.addListeners=function(elem,listeners){for(var evt in listeners)elem.addEventListener(evt,listeners[evt]);elem._eventListeners=listeners||null};
Dom.removeListeners=function(elem,listeners){if(!listeners)listeners=elem._eventListeners;for(var evt in listeners)elem.removeEventListener(evt,listeners[evt])};Dom.preventEvents=function(elem,events){var len=arguments.length;for(var i=1;i<len;++i)elem.addEventListener(arguments[i],Dom.preventDefault)};Dom.preventDefault=function(e){e.preventDefault();e.stopPropagation()};
Dom.scrollTopIntoView=function(view,px){if(!view)return 0;var h=view.clientHeight;if(!h)return 0;var sh=view.scrollHeight;if(sh<=h)return 0;var st=view.scrollTop;var pct25=h/4;var btm=st+h;var dest;if(px<st+pct25)dest=Math.round(px-pct25);else if(px>btm-pct25)dest=Math.round(px+pct25-h);else return 0;if(dest>sh-h)dest=sh-h;else if(dest<0)dest=0;if(dest===st)return 0;view.scrollTop=dest;return dest-st};window["Dom"]=Dom;
(function(){var obj={"map":Dom.map,"mapByAttribute":Dom.mapByAttribute,"getElementsByAttr":Dom.getElementsByAttr,"flatten":Dom.flatten,"firstMatch":Dom.firstMatch,"rebindEvents":Dom.rebindEvents,"setPxProp":Dom.setPxProp,"setWidth":Dom.setWidth,"setHeight":Dom.setHeight,"cssSize":Dom.cssSize,"appendChild":Dom.appendChild,"tree":Dom.tree,"removeParent":Dom.removeParent,"removeChildren":Dom.removeChildren,"removeNonChildElement":Dom.removeNonChildElement,"removeTextNodes":Dom.removeTextNodes,"replace":Dom.replace,
"setContent":Dom.setContent,"addClass":Dom.addClass,"addEffectClass":Dom.addEffectClass,"setTimeoutClass":Dom.setTimeoutClass,"addTimeoutClass":Dom.addTimeoutClass,"removeTimeoutClass":Dom.removeTimeoutClass,"tag":Dom.tag,"create":Dom.create,"div":Dom.div,"block":Dom.block,"icon":Dom.icon,"toggleAttribute":Dom.toggleAttribute,"toggleClass":Dom.toggleClass,"transferAttribute":Dom.transferAttribute,"addClasses":Dom.addClasses,"removeClasses":Dom.removeClasses,"addListeners":Dom.addListeners,"removeListeners":Dom.removeListeners,
"preventEvents":Dom.preventEvents,"preventDefault":Dom.preventDefault,"scrollTopIntoView":Dom.scrollTopIntoView};for(var key in obj)Dom[key]=obj[key]})();var Sheet={};Sheet._domLoaded=false;window.addEventListener("DOMContentLoaded",function(){Sheet._domLoaded=true},false);Sheet.inject=function(cssStr){var styleTag=null;if(cssStr){styleTag=document.createElement("style");styleTag.textContent=cssStr;var headerTag=document.head;if(Sheet._domLoaded){var otherTag=headerTag.getElementsByTagName("style")[0];if(otherTag)headerTag.insertBefore(styleTag,otherTag);else headerTag.appendChild(styleTag)}else headerTag.appendChild(styleTag)}return styleTag};
Sheet.buildRules=function(rules){var ary=arguments[1]?arguments:rules;var len=ary?ary.length:0;var str="";for(var i=0;i<len;i+=2){var ruleStr=Sheet.buildRule(ary[i],ary[i+1]);if(ruleStr)str+="\n"+ruleStr}return str};
Sheet.buildRule=function(selectors,styles,lvl){if(!selectors||!styles)return"";if(typeof selectors==="string"&&selectors.charAt(0)==="@")return selectors+" {\n\t"+Sheet.buildRule(styles[0],styles[1],lvl?lvl+1:1)+"\n}";var tab=lvl?"\t":"";return Sheet.buildSelectors(selectors)+" {\n\t"+tab+Sheet.buildStyles(styles)+"\n"+tab+"}"};Sheet.buildSelectors=function(selectors){return Array.isArray(selectors)?selectors.join(",\n"):selectors};
Sheet.buildStyles=function(styles){if(Array.isArray(styles))return styles.map(Sheet.buildStyle).join("\n\t");else return Sheet.buildStyle(styles)};Sheet.buildStyle=function(styleStr){if(styleStr){if(styleStr.charAt(styleStr.length-1)!==";")return styleStr+";";return styleStr}return""};var ElementWrapper=function(){};Ext.inherits(ElementWrapper,EventDispatcher);ElementWrapper.prototype._elem=null;ElementWrapper.prototype.getElement=function(){return this._elem};ElementWrapper.prototype.setParent=function(parent){if(parent){if(parent["getElement"])parent=parent["getElement"]();parent.appendChild(this._elem)}else{parent=this._elem.parentNode;if(parent)parent.removeChild(this._elem)}};ElementWrapper.prototype.getBoundingClientRect=function(){return this._elem.getBoundingClientRect()};
ElementWrapper.prototype.getMousePosition=function(e,retObj){if(!retObj)retObj={};var bounds=this.getBoundingClientRect();retObj["x"]=e.clientX-bounds["left"];retObj["y"]=e.clientY-bounds["top"];return retObj};ElementWrapper.prototype.addEventListener=function(type,listener,bool){this._elem.addEventListener(type,listener,false)};ElementWrapper.prototype.removeEventListener=function(type,listener,bool){this._elem.removeEventListener(type,listener,false)};window["ElementWrapper"]=ElementWrapper;
ElementWrapper._proto=ElementWrapper.prototype;ElementWrapper._proto["getElement"]=ElementWrapper._proto.getElement;ElementWrapper._proto["setParent"]=ElementWrapper._proto.setParent;ElementWrapper._proto["getBoundingClientRect"]=ElementWrapper._proto.getBoundingClientRect;ElementWrapper._proto["getMousePosition"]=ElementWrapper._proto.getMousePosition;ElementWrapper._proto["addEventListener"]=ElementWrapper._proto.addEventListener;ElementWrapper._proto["removeEventListener"]=ElementWrapper._proto.removeEventListener;var ElementList=function(elem,initObj){this._items=[];var options=typeof initObj=="string"?{"type":initObj}:initObj;if(elem)this.cloak(elem);else{this._elem=Dom.div();this._elem.classList.add("elem-list")}this.init(options)};Ext.inherits(ElementList,ElementWrapper);
ElementList._css=Sheet.buildRules(".elem-list",["display: inline-block"],".el-elem",["box-sizing: border-box","background-color: lightgrey","padding: 4px","height: 26px","margin-bottom: 2px"],".el-elem:hover",["background-color: grey"],".el-elem.selected",["box-shadow: inset 0 0 0 2px orange"]);Sheet.inject(ElementList._css);ElementList.prototype._items;ElementList.prototype._elemType="div";ElementList.prototype._tagName="DIV";ElementList.prototype._lazyInit=false;ElementList.prototype._elemDef=null;
ElementList.prototype.init=function(options){if(!options)return;var val=options["type"];if(val)this.setElementType(val);val=options["lazy"];if(val!=null)this._lazyInit=val?true:false;this.addListeners(options["listeners"]);var func=options["elemCreated"];if(typeof func=="function")this.listen("elemCreated",func);this._addDefinition("width",options["elemWidth"]);this._addDefinition("height",options["elemHeight"]);this._addDefinition("class",options["elemClass"]);var items=options["items"]||options["contexts"];
if(items)this.addElements(items);else{var texts=options["texts"];if(Array.isArray(texts))this.addTextElements(texts);else{val=options["itemCount"]||options["childCount"];if(typeof val=="number")this.setChildCount(val)}}};ElementList.prototype.addElement=function(txt,ctx){return this.insertElement(NaN,txt,ctx)};
ElementList.prototype.addElements=function(itemData){if(typeof itemData==="number")return this._addElements(itemData,[],[]);else if(typeof itemData==="string")return[this.addElement(itemData)];else if(Array.isArray(itemData))return this._addElements(itemData.length,[],itemData);return[]};ElementList.prototype.addTextElements=function(texts){if(typeof texts=="string")return[this.addElement(texts)];else return this._addElements(texts.length,texts,[])};
ElementList.prototype._addElements=function(count,texts,contexts){var arg={};var prevLen=this._items.length;var elems=new Array(count);for(var i=0;i<count;++i){var elem=elems[i]=this._newElement(texts[i]);arg["context"]=contexts[i];this._dispatchCreateEvent(elem,prevLen+i,arg);this._appendChild(elem);this._items.push(elem)}return elems};ElementList.prototype._appendChild=function(elem){if(!elem._suspended)this._elem.appendChild(elem)};
ElementList.prototype.insertElement=function(at,txt,ctx){var elem=this._newElement(txt);var curLen=this._items.length;var insertion=at>=0&&at<curLen;if(!insertion)at=curLen;this._dispatchCreateEvent(elem,at,ctx?{"context":ctx}:null);if(insertion){var nextElement=this.getNextVisibleElement(at-1);if(!this._lazyInit)this._elem.insertBefore(elem,nextElement);this._items.splice(at,0,elem)}else{this._appendChild(elem);this._items.push(elem)}return elem};ElementList.prototype.insertRow=ElementList.prototype.insertElement;
ElementList.prototype.insertCell=ElementList.prototype.insertElement;ElementList.prototype.removeAllChildren=function(){if(this._items.length){Dom.removeChildren(this._elem);this._items.length=0}};ElementList.prototype.removeChildAt=function(at){if(at<0||at>=this._items.length)return null;var elem=this._items[at];if(!elem._suspended)this._elem.removeChild(elem);return this._items.splice(at,1)[0]};
ElementList.prototype.removeChildren=function(count,opt_at){if(count==null)return this.removeAllChildren();var len=this._items.length;if(opt_at!=null){if(opt_at<=0)opt_at=0;else if(!(opt_at<len))return;if(opt_at+count>len)count=len-opt_at}else opt_at=len-count;if(count>=len)return this.removeAllChildren();var elems=this._items.splice(opt_at,count);for(var i=count;--i>=0;){var elem=elems[i];if(!elem._suspended)this._elem.removeChild(elem)}};
ElementList.prototype.replaceChildren=function(items){this.removeAllChildren();var len=items?items.length:0;if(!len)return;this.setElementType(items[0].tagName);this._items.length=len;if(Array.isArray(items))this.reorder(items);else{for(var i=0;i<len;++i)this._items[i]=items[i];this.reorder()}};ElementList.prototype.setChildCount=function(count){var len=this._items.length;if(count>len)this.addElements(count-len);else if(count<len)this.removeChildren(len-count)};
ElementList.prototype.updateChildList=function(){this._items.length=0;if(!this._elem)return;var chdr=this._elem.children;var len=chdr.length;if(len<=0)return;for(var i=0;i<len;++i){var child=chdr[i];if(this._tagName==child.tagName)this._items.push(child)}};ElementList.prototype.cloak=function(elem,elementType){if(elementType)this.setElementType(elementType);else if(elem&&elem.children[0])this.setElementType(elem.children[0].tagName);this._elem=elem;this.updateChildList()};
ElementList.prototype.setElementType=function(elementType){if(elementType&&elementType!==this._tagName){this._elemType=elementType.toLowerCase();this._tagName=elementType.toUpperCase()}};ElementList.prototype.getChild=function(at){return this._elem.children[at]||null};ElementList.prototype.getChildIndex=function(ref){return PosUt.getImmediateChildIndex(this._elem,ref)};ElementList.prototype.getChildCount=function(){return this._elem.children.length};ElementList.prototype.getChildren=function(){return this._elem.children};
ElementList.prototype.getChildTop=function(at){var child=this.getChild(at);if(child)if(this._elem.offsetParent===child.offsetParent)return child.offsetTop-this._elem.offsetTop-this._elem.clientTop;return 0};ElementList.prototype.getChildLeft=function(at){var child=this.getChild(at);if(child)if(this._elem.offsetParent===child.offsetParent)return child.offsetLeft-this._elem.offsetLeft-this._elem.clientLeft;return 0};ElementList.prototype.getItem=function(at){return this._items[at]||null};
ElementList.prototype.getItemIndex=function(ref){return this._items.indexOf(ref)};ElementList.prototype.getItemCount=function(){return this._items.length};ElementList.prototype.getAllItems=function(){return this._items};ElementList.prototype.setElementText=function(at,str){var elem=this._items[at];if(!elem)return;elem.textContent=str};ElementList.prototype.setItemText=ElementList.prototype.setElementText;
ElementList.prototype.searchElement=function(processor,ctx,forAllElements){var logic=this._getLogic(processor);if(ctx==null)ctx=this;var i,elem;var len=this._items.length;var elems=[];if(forAllElements)for(i=0;i<len;++i){elem=this._items[i];if(logic(elem,i,ctx))elems.push(elem)}else for(i=0;i<len;++i){elem=this._items[i];if(!elem._suspended)if(logic(elem,i,ctx))elems.push(elem)}return elems};ElementList.prototype.filterIn=function(processor,ctx){return this._filter(processor,true,ctx)};
ElementList.prototype.filterOut=function(processor,ctx){return this._filter(processor,false,ctx)};ElementList.prototype.clearFilter=function(){this.filterIn(ElementList._defaultAcceptAllLogic)};ElementList.prototype.sort=function(order,comparer){if(!comparer)comparer=ElementList.defaultElementComparer;Ary.sort(this._items,order,comparer);if(this._hasTheSameOrder(this._items))return false;var len=this._items.length;for(var i=0;i<len;++i){var elem=this._items[i];if(!elem._suspended)this._elem.appendChild(elem)}return true};
ElementList.prototype.reorder=function(elems){if(!elems)elems=this._items;else if(elems.length!==this._items.length)return;var len=elems.length;for(var i=0;i<len;++i){var elem=elems[i];if(!elem._suspended)this._elem.appendChild(elem);this._items[i]=elem}};
ElementList.prototype.moveChildDown=function(num){var len=this._items.length;if(!(num>0)||num>=len)return;var pn=this._elem;var chdr=this._items;var btmChunk=len-num;var i;if(num<=btmChunk)for(i=0;i<num;++i)pn.appendChild(chdr[i]);else for(i=len;--i>=num;)pn.insertBefore(chdr[i],pn.firstChild);var elems=chdr.splice(0,num);this._items=chdr.concat(elems)};
ElementList.prototype.getNextVisibleElement=function(elemRef){var at;if(typeof elemRef==="number")at=elemRef;else at=this._items.indexOf(elemRef);if(at<0)return null;var len=this._items.length;for(var i=at+1;i<len;++i){var elem=this._items[i];if(!elem._suspended)return elem}return null};
ElementList.prototype.suspendElement=function(elemRef,opt_bool){var elem=this._getItem(elemRef);if(!elem)return;if(opt_bool!==false)this._suspendElement(elem);else if(elem._suspended){var nextElement=this.getNextVisibleElement(elemRef);this._elem.insertBefore(elem,nextElement);elem._suspended=false}};ElementList.prototype.unsuspendElement=function(elemRef,opt_bool){this.suspendElement(elemRef,opt_bool===false)};ElementList.prototype.suspendAll=function(){this.filterOut(ElementList._defaultAcceptAllLogic)};
ElementList.prototype.unsuspendAll=ElementList.prototype.clearFilter;ElementList.prototype.enableLazyInitialization=function(opt_enabled){this._lazyInit=opt_enabled!==false};ElementList.prototype.getContentList=function(){return Ary.map(this.getChildren(),ElementList._getTextContent)};ElementList._getTextContent=function(elem){return elem.textContent};ElementList.prototype._addDefinition=function(prop,val){if(val){var def=this._elemDef;if(!def)def=this._elemDef={};def[prop]=val}};
ElementList.prototype._dispatchCreateEvent=function(elem,idx,arg){if(!arg)arg={};arg["elem"]=elem;arg["index"]=idx;this.dispatch("elemCreated",arg)};ElementList.prototype._newElement=function(txt){var elem=Dom.tag(this._elemType);var def=this._elemDef;if(def){if(def["width"])Dom.setWidth(elem,def["width"]);if(def["height"])Dom.setHeight(elem,def["height"]);if(def["class"])elem.classList.add(def["class"])}if(txt)elem.textContent=txt;elem._suspended=this._lazyInit;return elem};
ElementList.prototype._getItem=function(elemRef){if(typeof elemRef==="number")return this._items[elemRef]||null;return this._items.indexOf(elemRef)>=0?elemRef:null};ElementList.prototype._defaultSearchLogic=function(inputString,elem){return elem.textContent.indexOf(inputString)>=0};ElementList._defaultAcceptAllLogic=function(elem){return true};
ElementList.defaultElementComparer=function(elemA,elemB,order){var valA=elemA["rawValue"]!=null?elemA["rawValue"]:elemA.textContent;var valB=elemB["rawValue"]!=null?elemB["rawValue"]:elemB.textContent;if(valA===valB)return 0;return valA<valB?-order:order};
ElementList.numericElementComparer=function(elemA,elemB,order){var txtA=elemA.textContent;var txtB=elemB.textContent;if(txtA===txtB)return 0;var numA=+txtA;if(numA!==numA){numA=parseFloat(txtA.replace(/,/g,""));if(numA!==numA)numA=txtA}var numB=+txtB;if(numB!==numB){numB=parseFloat(txtB.replace(/,/g,""));if(numB!==numB)numB=txtB}return numA<numB?-order:order};
ElementList.prototype._getLogic=function(processor){if(!processor)return ElementList._defaultAcceptAllLogic;if(typeof processor=="string")return this._defaultSearchLogic.bind(null,processor);return processor};ElementList.prototype._suspendElement=function(elem){if(!elem._suspended){this._elem.removeChild(elem);elem._suspended=true}};
ElementList.prototype._filter=function(processor,filteringIn,ctx){var logic=this._getLogic(processor);if(ctx==null)ctx=this;var len=this._items.length;var elems=[];for(var i=0;i<len;++i){var elem=this._items[i];if(logic(elem,i,ctx)===filteringIn){this._elem.appendChild(elem);elem._suspended=false;elems.push(elem)}else this._suspendElement(elem)}return elems};
ElementList.prototype._hasTheSameOrder=function(elems){var nodes=this._elem.childNodes;var len=nodes.length;var elemLen=elems.length;var j=0;for(var i=0;i<len;++i){var elem;while(j<elemLen){elem=elems[j++];if(elem&&!elem._suspended)break;else elem=null}if(nodes[i]!==elem)return false}return true};window["ElementList"]=ElementList;ElementList._proto=ElementList.prototype;ElementList._proto["init"]=ElementList._proto.init;ElementList._proto["addElement"]=ElementList._proto.addElement;
ElementList._proto["addElements"]=ElementList._proto.addElements;ElementList._proto["addTextElements"]=ElementList._proto.addTextElements;ElementList._proto["insertElement"]=ElementList._proto.insertElement;ElementList._proto["insertRow"]=ElementList._proto.insertRow;ElementList._proto["insertCell"]=ElementList._proto.insertCell;ElementList._proto["removeAllChildren"]=ElementList._proto.removeAllChildren;ElementList._proto["removeChildAt"]=ElementList._proto.removeChildAt;
ElementList._proto["removeChildren"]=ElementList._proto.removeChildren;ElementList._proto["replaceChildren"]=ElementList._proto.replaceChildren;ElementList._proto["setChildCount"]=ElementList._proto.setChildCount;ElementList._proto["updateChildList"]=ElementList._proto.updateChildList;ElementList._proto["cloak"]=ElementList._proto.cloak;ElementList._proto["getChild"]=ElementList._proto.getChild;ElementList._proto["getChildIndex"]=ElementList._proto.getChildIndex;
ElementList._proto["getChildCount"]=ElementList._proto.getChildCount;ElementList._proto["getChildren"]=ElementList._proto.getChildren;ElementList._proto["getChildTop"]=ElementList._proto.getChildTop;ElementList._proto["getChildLeft"]=ElementList._proto.getChildLeft;ElementList._proto["getItem"]=ElementList._proto.getItem;ElementList._proto["getItemIndex"]=ElementList._proto.getItemIndex;ElementList._proto["getItemCount"]=ElementList._proto.getItemCount;ElementList._proto["getAllItems"]=ElementList._proto.getAllItems;
ElementList._proto["setElementText"]=ElementList._proto.setElementText;ElementList._proto["setItemText"]=ElementList._proto.setItemText;ElementList._proto["searchElement"]=ElementList._proto.searchElement;ElementList._proto["filterIn"]=ElementList._proto.filterIn;ElementList._proto["filterOut"]=ElementList._proto.filterOut;ElementList._proto["clearFilter"]=ElementList._proto.clearFilter;ElementList._proto["sort"]=ElementList._proto.sort;ElementList._proto["reorder"]=ElementList._proto.reorder;
ElementList._proto["moveChildDown"]=ElementList._proto.moveChildDown;ElementList._proto["getNextVisibleElement"]=ElementList._proto.getNextVisibleElement;ElementList._proto["suspendElement"]=ElementList._proto.suspendElement;ElementList._proto["unsuspendElement"]=ElementList._proto.unsuspendElement;ElementList._proto["suspendAll"]=ElementList._proto.suspendAll;ElementList._proto["unsuspendAll"]=ElementList._proto.unsuspendAll;ElementList._proto["enableLazyInitialization"]=ElementList._proto.enableLazyInitialization;
ElementList._proto["getContentList"]=ElementList._proto.getContentList;ElementList["defaultElementComparer"]=ElementList.defaultElementComparer;ElementList["numericElementComparer"]=ElementList.numericElementComparer;var SubTable=function(elemRef){var elem;if(elemRef)if(typeof elemRef=="string")elem=Dom.tag(elemRef);else elem=elemRef;else elem=Dom.tag("tbody");SubTable["base"](this,null,elem,"tr");this._render=SubTable._defaultCellRenderer};Ext.inherits(SubTable,ElementList);SubTable.prototype._colCount=0;SubTable.prototype._defaultRowHeight=null;SubTable.prototype._render;
SubTable.prototype.addColumns=function(opt_count){if(opt_count==null)opt_count=1;else if(opt_count<=0)return null;this._colCount+=opt_count;var rows=this.getRows();for(var r=rows.length;--r>=0;){var tr=rows[r];for(var c=0;c<opt_count;++c)tr.insertCell(-1)}};
SubTable.prototype.removeColumns=function(opt_count){if(opt_count==null||opt_count>=this._colCount)return this.removeAllColumns();if(opt_count<=0)return;this._colCount-=opt_count;var rows=this.getRows();for(var r=rows.length;--r>=0;)Dom.removeChildren(rows[r],opt_count)};SubTable.prototype.removeAllColumns=function(){if(this._colCount<=0)return;this._colCount=0;this.removeAllRows()};
SubTable.prototype.setColumnCount=function(val){if(val>=this._colCount)this.addColumns(val-this._colCount);else this.removeColumns(this._colCount-val)};SubTable.prototype.addRows=function(count){var rows=null;if(count==null)count=1;if(count>0){rows=new Array(count);for(var r=0;r<count;++r){var tr=rows[r]=this.insertRow(-1);for(var c=this._colCount;--c>=0;)tr.insertCell(-1)}if(this._defaultRowHeight!=null)this._applyDefaultRowHeight(rows,this._defaultRowHeight+"px")}return rows||[]};
SubTable.prototype.removeRows=function(count){if(count==null||count>=this.getRowCount())return this.removeAllRows();if(count>0)this.removeChildren(count)};SubTable.prototype.removeAllRows=function(){this.removeChildren()};SubTable.prototype.setRowCount=function(val){var rowCount=this.getRowCount();if(val>=rowCount)this.addRows(val-rowCount);else this.removeRows(rowCount-val)};
SubTable.prototype.setDefaultRowHeight=function(val){if(!val)val=null;if(val===this._defaultRowHeight)return;this._defaultRowHeight=val;var minHeight=this._defaultRowHeight!=null?this._defaultRowHeight+"px":"";this._applyDefaultRowHeight(this.getRows(),minHeight)};SubTable.prototype.getColumnCount=function(){return this._colCount};SubTable.prototype.getRowCount=function(){return this.getChildCount()};SubTable.prototype.getCell=function(c,r){var tr=this.getRow(r);if(tr)return tr.cells[c]||null;return null};
SubTable.prototype.getCellsInColumn=function(c){if(c<0||c>=this._colCount)return null;var rows=this.getRows();var rowCount=rows.length;var ary=new Array(rowCount);for(var r=0;r<rowCount;++r)ary[r]=rows[r].cells[c];return ary};SubTable.prototype.getCellsInRow=function(r){var tr=this.getRow(r);return tr?tr.cells:null};
SubTable.prototype.getAllCells=function(){var rows=this.getRows();var rowCount=rows.length;var colCount=this._colCount;var cellCount=0;var ary=new Array(rowCount*colCount);for(var r=0;r<rowCount;++r){var tr=rows[r];for(var c=0;c<colCount;++c)ary[cellCount++]=tr.cells[c]}return ary};SubTable.prototype.getAllRows=function(){return this.getChildren()};SubTable.prototype.getRows=SubTable.prototype.getAllRows;SubTable.prototype.getRow=function(r){return this.getChild(r)};
SubTable.prototype.getTextContents=function(){var rows=this.getRows();var rowCount=rows.length;var rowContents=new Array(rowCount);for(var r=0;r<rowCount;++r){var row=rows[r];var colContents=new Array(this._colCount);rowContents[r]=colContents;for(var c=0;c<this._colCount;++c)colContents[c]=row.cells[c].textContent}return rowContents};SubTable.prototype.getCellTextContent=function(c,r){var cell=this.getCell(c,r);if(cell)return cell.textContent;return""};
SubTable.prototype.getColumnTextContent=function(c){var rows=this.getRows();var rowCount=rows.length;if(c>=0&&c<this._colCount&&rowCount>0){var str=rows[0].cells[c].textContent;for(var r=1;r<rowCount;++r)str+="\n"+rows[r].cells[c].textContent;return str}return""};SubTable.prototype.getRowTextContent=function(r){var tr=this.getRow(r);if(tr&&this._colCount>0){var str=tr.cells[0].textContent;for(var c=1;c<this._colCount;++c)str+="\t"+tr.cells[c].textContent;return str}return""};
SubTable.prototype.getTableTextContent=function(){var rowCount=this.getRows().length;if(rowCount>0){var str=this.getRowTextContent(0);for(var r=1;r<rowCount;++r)str+="\n"+this.getRowTextContent(r);return str}return""};
SubTable.prototype.toString=function(){var str=this.getElement().outerHTML;str=str.replace(/><tr/g,">\n\t<tr");str=str.replace(/><td/g,">\n\t\t<td");str=str.replace(/><td/g,">\n\t\t<th");str=str.replace(/><\/tr/g,">\n\t</tr");var tagName=this.getElement().tagName.toLowerCase();str=str.replace("</"+tagName,"\n</"+tagName);return str};
SubTable.prototype.getColumnIndex=function(e){if(e){var tgt=e.target;if(this._elem.contains(tgt)){var tdElem=PosUt.closestTagName(tgt,"TD");if(!tdElem)tdElem=PosUt.closestTagName(tgt,"TH");if(tdElem)return Ary.indexOf(tdElem.parentElement.children,tdElem)}else{var rows=this.getRows();var cells=rows[0]?rows[0].cells:null;if(cells){var pos=PosUt.getRelativePosition(e,this._elem);var x=pos["x"];if(x>=0){var len=cells.length;for(var i=0;i<len;++i){x-=cells[i].offsetWidth;if(x<0)return i}}}}}return-1};
SubTable.prototype.getRowIndex=function(e){if(e){var at=this.getChildIndex(e);if(at>=0)return at;else{var rows=this.getRows();if(rows){var pos=PosUt.getRelativePosition(e,this._elem);var y=pos["y"];if(y>=0){var len=rows.length;for(var i=0;i<len;++i){y-=rows[i].offsetHeight;if(y<0)return i}}}}}return-1};SubTable.prototype.toCellIndex=function(colIndex,rowIndex){if(colIndex>=0&&colIndex<this._colCount)if(rowIndex>=0&&rowIndex<this.getRowCount())return colIndex+rowIndex*this._colCount;return-1};
SubTable.prototype.toIndexPoint=function(cellIndex,pt){if(!pt)pt=[0,0];var rowIndex=-1;var colIndex=-1;if(cellIndex>=0&&this._colCount){rowIndex=cellIndex/this._colCount|0;if(rowIndex<this.getRowCount())colIndex=cellIndex-rowIndex*this._colCount}pt[0]=colIndex;pt[1]=rowIndex;return pt};SubTable.prototype.getColumnLeft=function(colIndex,rowIndex){var cell=this.getCell(colIndex,rowIndex?rowIndex:0);if(cell)return cell.offsetLeft;return NaN};
SubTable.prototype.getRowTop=function(rowRef){var row=null;if(typeof rowRef==="number")row=this.getRow(rowRef);else row=PosUt.closestTagName(rowRef,"TR");return row?row.offsetTop:NaN};SubTable.prototype.getCellPosition=function(cell,ret_obj){if(!ret_obj)ret_obj={};ret_obj["x"]=cell.offsetLeft;var pn=cell.parentNode;ret_obj["y"]=pn?pn.offsetTop:NaN;return ret_obj};
SubTable.prototype.setContent=function(userInput,opt_hSplitter){if(!userInput)return;var userRows=typeof userInput==="string"?Ary.toTable(userInput,null,opt_hSplitter):userInput;var colCount=this._colCount;for(var i=userRows.length;--i>=0;){var uRow=userRows[i];if(uRow.length!==colCount)userRows.splice(i,1)}this.setRowCount(userRows.length);var rows=this.getRows();for(var r=userRows.length;--r>=0;){var tr=rows[r];if(tr){var userRow=userRows[r];for(var c=userRow.length;--c>=0;){var td=tr.cells[c];
if(td){var userData=userRow[c];td["rawValue"]=userData!=null?userData:null;if(this._render(td,userData,c,r)===false)SubTable._defaultCellRenderer(td,userData,c,r)}}}}};SubTable.prototype.setCellRenderer=function(func){this._render=func||SubTable._defaultCellRenderer};SubTable.prototype.cloak=function(elem,opt_elementType){SubTable["base"](this,"cloak",elem,"tr");var rows=elem.getElementsByTagName("TR");this._colCount=rows[0]?rows[0].children.length:0};
SubTable.prototype.spanBlock=function(c1,c2,r1,r2){var cell=null;for(var c=c2;c>=c1;--c)for(var r=r2;r>=r1;--r){cell=this.getCell(c,r);if(cell)cell.style.display="none"}if(cell){cell.setAttribute("colspan",c2-c1+1);cell.setAttribute("rowspan",r2-r1+1);cell.style.display=""}return cell};
SubTable.parseTableContent=function(tbl){if(!tbl)return null;var tbody=tbl.tagName=="TBODY"?tbl:tbl.getElementsByTagName("TBODY")[0];if(!tbody)if(tbl.tagName=="TABLE")tbody=tbl;if(!tbody)return null;var trs=tbody.getElementsByTagName("TR");var rowCount=trs.length;var rows=new Array(rowCount);for(var i=0;i<rowCount;++i){var tds=trs[i].getElementsByTagName("TD");var colCount=tds.length;var columns=new Array(colCount);rows[i]=columns;for(var j=0;j<colCount;++j)columns[j]=tds[j].textContent}return rows};
SubTable.prototype._applyDefaultRowHeight=function(rows,minHeight){for(var r=rows.length;--r>=0;)rows[r].style.height=minHeight};SubTable._defaultCellRenderer=function(tdCell,val,c,r){if(val!=null)if(val["nodeType"])tdCell.appendChild(val);else tdCell.textContent=val;else tdCell.textContent=""};window["SubTable"]=SubTable;SubTable._proto=SubTable.prototype;SubTable._proto["addRows"]=SubTable._proto.addRows;SubTable._proto["removeRows"]=SubTable._proto.removeRows;SubTable._proto["removeAllRows"]=SubTable._proto.removeAllRows;
SubTable._proto["setRowCount"]=SubTable._proto.setRowCount;SubTable._proto["setDefaultRowHeight"]=SubTable._proto.setDefaultRowHeight;SubTable._proto["getColumnCount"]=SubTable._proto.getColumnCount;SubTable._proto["getRowCount"]=SubTable._proto.getRowCount;SubTable._proto["getCell"]=SubTable._proto.getCell;SubTable._proto["getCellsInColumn"]=SubTable._proto.getCellsInColumn;SubTable._proto["getCellsInRow"]=SubTable._proto.getCellsInRow;SubTable._proto["getAllCells"]=SubTable._proto.getAllCells;
SubTable._proto["getAllRows"]=SubTable._proto.getAllRows;SubTable._proto["getRows"]=SubTable._proto.getRows;SubTable._proto["getRow"]=SubTable._proto.getRow;SubTable._proto["getTextContents"]=SubTable._proto.getTextContents;SubTable._proto["getCellTextContent"]=SubTable._proto.getCellTextContent;SubTable._proto["getColumnTextContent"]=SubTable._proto.getColumnTextContent;SubTable._proto["getRowTextContent"]=SubTable._proto.getRowTextContent;SubTable._proto["getTableTextContent"]=SubTable._proto.getTableTextContent;
SubTable._proto["toString"]=SubTable._proto.toString;SubTable._proto["getColumnIndex"]=SubTable._proto.getColumnIndex;SubTable._proto["getRowIndex"]=SubTable._proto.getRowIndex;SubTable._proto["getColumnLeft"]=SubTable._proto.getColumnLeft;SubTable._proto["toCellIndex"]=SubTable._proto.toCellIndex;SubTable._proto["toIndexPoint"]=SubTable._proto.toIndexPoint;SubTable._proto["getRowTop"]=SubTable._proto.getRowTop;SubTable._proto["getCellPosition"]=SubTable._proto.getCellPosition;
SubTable._proto["setContent"]=SubTable._proto.setContent;SubTable._proto["setCellRenderer"]=SubTable._proto.setCellRenderer;SubTable._proto["cloak"]=SubTable._proto.cloak;SubTable._proto["spanBlock"]=SubTable._proto.spanBlock;SubTable["parseTableContent"]=SubTable.parseTableContent;var Table=function(elem,opt_colCount,opt_rowCount){var t=this;t._internalTableComparer=t._internalTableComparer.bind(t);t._onClickHeader=t._onClickHeader.bind(t);if(elem&&elem.nodeType===1)t._elem=elem;else{t._elem=Dom.block("inline-table");if(typeof elem=="number"){if(typeof opt_colCount==="number")opt_rowCount=opt_colCount;opt_colCount=elem;elem=null}}if(!t._elem.id)t._elem.id="table_"+Table._runningId++;t._elem.classList.add("js-table");t._table=Dom.tag("table");t._colgroup=Dom.tag("colgroup");
t._tbody=new SubTable("tbody");t._subs=[t._tbody];var options=null;if(opt_colCount&&typeof opt_colCount!=="number"){options=opt_colCount;opt_colCount=0}if(opt_colCount>0)t.addColumns(opt_colCount);if(opt_rowCount>0)t.addRows(opt_rowCount);t._table.appendChild(t._colgroup);t._table.appendChild(t._tbody.getElement());t.fixateTableWidth();t.init(options);t._elem.appendChild(t._table)};Ext.inherits(Table,ElementWrapper);
Table._css=Sheet.buildRules(".inline-table",["display: inline-block"],[".borders-collapsed table",".border-collapsed table"],["border-collapse: collapse"],[".js-table thead td",".js-table thead th"],["cursor: pointer","text-align: center","position: relative"],".js-table .sorted:after",['content: " "',"position: absolute","left: calc(50% - 0.5em)","top: 0","width: 0","height: 0","border: solid 5px transparent"],".js-table .ascending:after",["border-top-width: 0","border-bottom-color: black"],".js-table .descending:after",
["border-bottom-width: 0","border-top-color: black"],".filling-table table",["width: 100%","height: 100%","table-layout: fixed","border-collapse: collapse"]);Sheet.inject(Table._css);Table._runningId=1;Table.prototype._table;Table.prototype._colgroup;Table.prototype._colCount=0;Table.prototype._defaultRowHeight=null;Table.prototype._defaultColumnWidth=null;Table.prototype._autoWidthUpdate=false;Table.prototype._sortedColumn=-1;Table.prototype._sortOrder=0;Table.prototype._sortLogic;
Table.prototype._defaultSortLogic=ElementList.defaultElementComparer;Table.prototype._tbody;Table.prototype._thead;Table.prototype._tfoot;Table.prototype._subs;Table.prototype.getTableElement=function(){return this._table};Table.prototype.setCRWH=function(col,row,width,height){this.setColumnCount(col);this.setRowCount(row);this.setSize(width,height)};
Table.prototype.init=function(options){if(!options)return;var colWidth=options["colWidth"]||options["cellWidth"];if(colWidth)this.setDefaultColumnWidth(colWidth);var rowHeight=options["rowHeight"]||options["cellHeight"];if(rowHeight)this.setDefaultRowHeight(rowHeight);var colCount=options["colCount"];if(colCount)this.setColumnCount(colCount);var rowCount=options["rowCount"];if(rowCount)this.setRowCount(rowCount);var tableWidth=options["width"]||options["tableWidth"];if(tableWidth&&this._colCount)this.setDefaultColumnWidth(tableWidth/
this._colCount|0);var tableHeight=options["height"]||options["tableHeight"];if(tableHeight){rowCount=this.getRowCount();if(rowCount)this.setDefaultRowHeight(tableHeight/rowCount|0)}};
Table.prototype.addColumns=function(opt_count){if(opt_count==null)opt_count=1;else if(opt_count<=0)return null;var cols=[];var c;for(c=opt_count;--c>=0;){var col=document.createElement("col");this._colgroup.appendChild(col);cols[c]=col}this._colCount+=opt_count;if(this._defaultColumnWidth!=null){var minWidth=this._defaultColumnWidth+"px";for(c=opt_count;--c>=0;)cols[c].style.width=minWidth}for(var i=this._subs.length;--i>=0;)this._subs[i].addColumns(opt_count);this._updateTableWidth();return cols};
Table.prototype.removeColumns=function(opt_count){if(opt_count==null||opt_count>=this._colCount)return this.removeAllColumns();if(opt_count<=0)return;this._colCount-=opt_count;Dom.removeChildren(this._colgroup,opt_count);for(var i=this._subs.length;--i>=0;)this._subs[i].removeColumns(opt_count);this._updateTableWidth()};
Table.prototype.removeAllColumns=function(){if(this._colCount<=0)return;this._colCount=0;Dom.removeChildren(this._colgroup);for(var i=this._subs.length;--i>=0;)this._subs[i].removeAllColumns();this._updateTableWidth()};Table.prototype.setColumnCount=function(val){if(val>=this._colCount)this.addColumns(val-this._colCount);else this.removeColumns(this._colCount-val)};Table.prototype.addRows=function(opt_count){return this._tbody.addRows(opt_count)};Table.prototype.removeRows=function(opt_count){return this._tbody.removeRows(opt_count)};
Table.prototype.removeAllRows=function(){return this._tbody.removeAllRows()};Table.prototype.setRowCount=function(val){return this._tbody.setRowCount(val)};Table.prototype.getColumnCount=function(){return this._colCount};Table.prototype.getRowCount=function(){return this._tbody.getRowCount()};Table.prototype.getCell=function(c,r){return this._tbody.getCell(c,r)};Table.prototype.getCellsInColumn=function(c){return this._tbody.getCellsInColumn(c)};Table.prototype.getCellsInRow=function(r){return this._tbody.getCellsInRow(r)};
Table.prototype.getAllCells=function(){return this._tbody.getAllCells()};Table.prototype.getAllRows=function(){return this._tbody.getAllRows()};Table.prototype.getRows=Table.prototype.getAllRows;Table.prototype.getRow=function(r){return this._tbody.getRow(r)};Table.prototype.spanBlock=function(c1,c2,r1,r2){return this._tbody.spanBlock(c1,c2,r1,r2)};
Table.prototype.spanHorizontally=function(r,val){var spanVal=0;if(val)if(typeof val=="number")spanVal=val>1?val-1:0;else spanVal=this._colCount;else if(val==null)spanVal=this._colCount;return this._tbody.spanBlock(0,spanVal,r,r)};Table.prototype.setColMinWidths=function(val,opt_at){this._setColStyle("width",val,opt_at);this._updateTableWidth()};Table.prototype.setColumnWidths=Table.prototype.setColMinWidths;
Table.prototype.setColBackgroundColors=function(val,opt_at){this._setColStyle("background-color",val,opt_at)};Table.prototype.setColBGColors=Table.prototype.setColBackgroundColors;Table.prototype.setColBorders=function(val,opt_at){this._setColStyle("border",val,opt_at)};Table.prototype.setSize=function(width,height){if(this._colCount<0)this.addColumns();if(this.getRowCount()<0)this.addRows();this.setCellSize(width/this._colCount|0,height/this.getRowCount()|0)};
Table.prototype.setCellSize=function(defaultWidth,defaultHeight){this.setDefaultColumnWidth(defaultWidth);this.setDefaultRowHeight(defaultHeight)};Table.prototype.setDefaultColumnWidth=function(val){if(!val)val=null;if(val===this._defaultColumnWidth)return;this._defaultColumnWidth=val;if(this._colCount>0)this._setColStyle("width",this._defaultColumnWidth||"");this._updateTableWidth()};
Table.prototype.setDefaultRowHeight=function(val){if(!val)val=null;if(val===this._defaultRowHeight)return;this._defaultRowHeight=val;for(var i=this._subs.length;--i>=0;)this._subs[i].setDefaultRowHeight(val)};
Table.prototype.distributeColumnWidth=function(){if(this._colCount<=1)return;var txtRows=this._tbody.getTextContents();var rowCount=txtRows.length;if(!rowCount)return;var maxWidths=new Array(this._colCount);var txtRow=txtRows[0];for(var c=0;c<this._colCount;++c)maxWidths[c]=txtRow[c].length;for(var r=1;r<rowCount;++r){txtRow=txtRows[r];for(c=0;c<this._colCount;++c)if(maxWidths[c]<txtRow[c].length)maxWidths[c]=txtRow[c].length}var longestColumn=0;var maxWidth=maxWidths[0];for(c=this._colCount;--c>=
1;)if(maxWidth<maxWidths[c]){maxWidth=maxWidths[c];longestColumn=c}for(c=this._colCount;--c>=0;)maxWidths[c]=Math.floor(maxWidths[c]/maxWidth*100)+"%";maxWidths[longestColumn]="";this.setColumnWidths(maxWidths)};
Table.prototype.log=function(opt_rowLimit){var trs=this.getRows();var rowCount=trs.length;if(!opt_rowLimit||opt_rowLimit<=0)opt_rowLimit=rowCount;var c;var colNames=new Array(this._colCount);for(c=0;c<this._colCount;++c){var hCell=this.getHeaderCell(c,0);var hStr=hCell?hCell.textContent:"";colNames[c]=hStr||""+c}var rows=[];for(var r=0;r<rowCount;++r){var cols={};for(c=0;c<this._colCount;++c)cols[colNames[c]]=trs[r].cells[c].textContent;if(rows.length<opt_rowLimit)rows.push(cols);else break}console.table(rows)};
Table.prototype.getTextContents=function(){return this._tbody.getTextContents()};Table.prototype.getCellTextContent=function(c,r){return this._tbody.getCellTextContent(c,r)};Table.prototype.getColumnTextContent=function(c){return this._tbody.getColumnTextContent(c)};Table.prototype.getRowTextContent=function(r){return this._tbody.getRowTextContent(r)};Table.prototype.getTableTextContent=function(){return this._tbody.getTableTextContent()};
Table.prototype.fixateTableWidth=function(opt_bool){this._autoWidthUpdate=opt_bool!==false;if(this._autoWidthUpdate)this._updateTableWidth();else if(this._table.style.width)this._table.style.width=""};Table.prototype.loosenTableWidth=function(opt_bool){this.fixateTableWidth(opt_bool===false)};Table.prototype.addHeaderRows=function(opt_count){this._addHeader();return this._thead.addRows(opt_count)};Table.prototype.getHeaderCell=function(c,r){if(this._thead)return this._thead.getCell(c,r);return null};
Table.prototype.getAllHeaderCells=function(){if(!this._thead)return[];return this._thead.getAllCells()};Table.prototype.removeHeaderRows=function(opt_count){if(this._thead)return this._thead.removeRows(opt_count)};Table.prototype.addFooterRows=function(opt_count){this._addFooter();return this._tfoot.addRows(opt_count)};Table.prototype.getFooterCell=function(c,r){if(this._tfoot)return this._tfoot.getCell(c,r);return null};Table.prototype.getAllFooterCells=function(){if(!this._tfoot)return[];return this._tfoot.getAllCells()};
Table.prototype.removeFooterRows=function(opt_count){if(this._tfoot)return this._tfoot.removeRows(opt_count)};
Table.prototype.sort=function(opt_order,colIndex){var t=this;if(typeof colIndex=="string"){var tmp=opt_order;opt_order=colIndex;colIndex=tmp}var prevCol=t._sortedColumn;if(colIndex!=null)t._sortedColumn=colIndex;var validCol=t._sortedColumn>=0&&t._sortedColumn<t._colCount;var sortOrder=Ary.getSortOrder(opt_order);if(t._thead){var rows=t._thead.getRows();var r,td;if(t._sortOrder&&prevCol>=0&&prevCol<t._colCount){var prevOrderClass=t._sortOrder===1?"ascending":"descending";for(r=rows.length;--r>=0;){td=
rows[r].cells[prevCol];if(td){td.classList.remove(prevOrderClass);td.classList.remove("sorted")}}}if(sortOrder&&validCol){var newOrderClass=sortOrder===1?"ascending":"descending";for(r=rows.length;--r>=0;){td=rows[r].cells[t._sortedColumn];if(td){td.classList.add(newOrderClass);td.classList.add("sorted")}}}}t._sortLogic=t._defaultSortLogic;if(validCol){t._sortOrder=validCol?sortOrder:0;var colElem=t._colgroup.children[t._sortedColumn];if(colElem&&colElem._sortLogic)t._sortLogic=colElem._sortLogic}else t._sortOrder=
0;t._tbody.sort(t._sortOrder,t._internalTableComparer)};Table.prototype.setSortLogic=function(comparer,colIndex){var comp=null;if(typeof comparer==="string"){if(comparer==="number")comp=ElementList.numericElementComparer}else comp=comparer;if(colIndex==null)this._defaultSortLogic=comp?comp:ElementList.defaultElementComparer;else{var colElem=this._colgroup.children[colIndex];if(colElem)colElem._sortLogic=comp?comp:ElementList.defaultElementComparer}};Table.prototype.getColumnIndex=function(e){return this._tbody.getColumnIndex(e)};
Table.prototype.getRowIndex=function(e){return this._tbody.getRowIndex(e)};Table.prototype.toCellIndex=function(colIndex,rowIndex){return this._tbody.toCellIndex(colIndex,rowIndex)};Table.prototype.toIndexPoint=function(cellIndex,pt){return this._tbody.toIndexPoint(cellIndex,pt)};Table.prototype.getColumnLeft=function(colIndex,rowIndex){return this._tbody.getColumnLeft(colIndex,rowIndex)};Table.prototype.getRowTop=function(rowRef){return this._tbody.getRowTop(rowRef)+this._tbody.getElement().offsetTop};
Table.prototype.getCellPosition=function(cell,ret_obj){ret_obj=this._tbody.getCellPosition(cell,ret_obj);ret_obj["y"]+=this._tbody.getElement().offsetTop;return ret_obj};Table.prototype.setContent=function(userRows,opt_hSplitter){if(typeof userRows==="string")userRows=Ary.toTable(userRows,null,opt_hSplitter);if(Array.isArray(userRows)&&!Ary.is2DArray(userRows))userRows=[userRows];this._adjustColCount(userRows);this._tbody.setContent(userRows);if(this._sortOrder)this.sort(this._sortOrder,this._sortedColumn)};
Table.prototype.setHeaderContent=function(userRows,opt_hSplitter){if(typeof userRows==="string")userRows=Ary.toTable(userRows,null,opt_hSplitter);if(Array.isArray(userRows)&&!Ary.is2DArray(userRows))userRows=[userRows];this._adjustColCount(userRows);this._addHeader();this._thead.setContent(userRows)};
Table.prototype.setFooterContent=function(userRows,opt_hSplitter){if(typeof userRows==="string")userRows=Ary.toTable(userRows,null,opt_hSplitter);if(Array.isArray(userRows)&&!Ary.is2DArray(userRows))userRows=[userRows];this._adjustColCount(userRows);this._addFooter();this._tfoot.setContent(userRows)};
Table.prototype.rebuild=function(userRows,headerRows,footerRows,opt_hSplitter){this.removeAllColumns();this.setContent(userRows,opt_hSplitter);if(headerRows)this.setHeaderContent(headerRows,opt_hSplitter);if(footerRows)this.setFooterContent(footerRows,opt_hSplitter)};
Table.prototype.cloak=function(tblElem){if(!tblElem)return;if(!tblElem.parentElement)return;if(tblElem.tagName!=="TABLE")return;this._elem=tblElem.parentElement;this._elem.classList.add("js-table");this._table=tblElem;var elems=tblElem.getElementsByTagName("COLGROUP");this._colgroup=elems[0]?elems[0]:document.createElement("colgroup");elems=tblElem.getElementsByTagName("TR");this._colCount=elems[0]?elems[0].children.length:0;this._autoWidthUpdate=this._table.getAttribute("width")?true:false;elems=
tblElem.getElementsByTagName("TBODY");if(elems[0])this._tbody.cloak(elems[0]);elems=tblElem.getElementsByTagName("THEAD");if(elems[0])this._addHeader(elems[0]);elems=tblElem.getElementsByTagName("TFOOT");if(elems[0])this._addFooter(elems[0])};Table.prototype.getBody=function(){return this._tbody};Table.prototype.getHeader=function(){return this._thead};Table.prototype.getFooter=function(){return this._tfoot};Table.parseTableContent=SubTable.parseTableContent;
Table.prototype._addHeader=function(opt_elem){var t=this;if(!t._thead){t._thead=new SubTable(opt_elem?opt_elem:"thead");t._subs.push(t._thead);t._thead.setColumnCount(t._colCount);t._thead.setDefaultRowHeight(t._defaultRowHeight);t._thead.addEventListener("click",t._onClickHeader);t._table.insertBefore(t._thead.getElement(),t._tbody.getElement())}else if(opt_elem)t._thead.cloak(opt_elem)};
Table.prototype._addFooter=function(opt_elem){var t=this;if(!t._tfoot){t._tfoot=new SubTable(opt_elem?opt_elem:"tfoot");t._subs.push(t._tfoot);t._tfoot.setColumnCount(t._colCount);t._tfoot.setDefaultRowHeight(t._defaultRowHeight);t._table.appendChild(t._tfoot.getElement())}else if(opt_elem)t._tfoot.cloak(opt_elem)};
Table.prototype._setColStyle=function(prop,val,opt_at){if(val==null)val="";var c,col;if(val instanceof Array){var count=val.length<this._colCount?val.length:this._colCount;for(c=count;--c>=0;){var str=val[c];if(typeof str==="number")str=str+"px";if(str){col=this._colgroup.children[c];col.style[prop]=str}}}else{if(typeof val==="number")val=val+"px";if(typeof opt_at==="number"){col=this._colgroup.children[opt_at];if(col)col.style[prop]=val}else for(c=this._colCount;--c>=0;){col=this._colgroup.children[c];
col.style[prop]=val}}};Table.prototype._updateTableWidth=function(){if(!this._autoWidthUpdate)return;var fixedWidth=true;var totalWidth=0;for(var c=this._colCount;--c>=0;){var col=this._colgroup.children[c];var str=col.style.width;if(!str){fixedWidth=false;break}totalWidth+=parseFloat(str)}if(fixedWidth&&totalWidth>0)this._table.style.width=totalWidth+"px";else if(this._table.style.width)this._table.style.width=""};
Table.prototype._adjustColCount=function(ary){if(this._colCount>0)return this._colCount;var colCount=0;var rowCount=ary.length;for(var r=0;r<rowCount;++r){var cols=ary[r];if(cols.length>colCount)colCount=cols.length}this.setColumnCount(colCount);return colCount};Table.prototype._internalTableComparer=function(trA,trB,order){var tdA=trA.cells[this._sortedColumn];var tdB=trB.cells[this._sortedColumn];return this._sortLogic(tdA,tdB,order)};
Table.prototype._onClickHeader=function(e){var colIndex=this._thead.getColumnIndex(e);if(colIndex<0)return;var sortOrder=1;if(colIndex===this._sortedColumn)if(this._sortOrder===1)sortOrder=-1;this.sort(sortOrder,colIndex);Dom.preventDefault(e)};window["Table"]=Table;
(function(){var pt=Table.prototype;var obj={"getTableElement":pt.getTableElement,"setCRWH":pt.setCRWH,"init":pt.init,"addColumns":pt.addColumns,"removeColumns":pt.removeColumns,"removeAllColumns":pt.removeAllColumns,"setColumnCount":pt.setColumnCount,"addRows":pt.addRows,"removeRows":pt.removeRows,"removeAllRows":pt.removeAllRows,"setRowCount":pt.setRowCount,"getColumnCount":pt.getColumnCount,"getRowCount":pt.getRowCount,"getCell":pt.getCell,"getCellsInColumn":pt.getCellsInColumn,"getCellsInRow":pt.getCellsInRow,
"getAllCells":pt.getAllCells,"getAllRows":pt.getAllRows,"getRows":pt.getRows,"getRow":pt.getRow,"spanBlock":pt.spanBlock,"setColMinWidths":pt.setColMinWidths,"setColumnWidths":pt.setColumnWidths,"setColBackgroundColors":pt.setColBackgroundColors,"setColBGColors":pt.setColBGColors,"setColBorders":pt.setColBorders,"setSize":pt.setSize,"setCellSize":pt.setCellSize,"setDefaultColumnWidth":pt.setDefaultColumnWidth,"setDefaultRowHeight":pt.setDefaultRowHeight,"distributeColumnWidth":pt.distributeColumnWidth,
"log":pt.log,"getTextContents":pt.getTextContents,"getCellTextContent":pt.getCellTextContent,"getColumnTextContent":pt.getColumnTextContent,"getRowTextContent":pt.getRowTextContent,"getTableTextContent":pt.getTableTextContent,"fixateTableWidth":pt.fixateTableWidth,"loosenTableWidth":pt.loosenTableWidth,"addHeaderRows":pt.addHeaderRows,"getHeaderCell":pt.getHeaderCell,"getAllHeaderCells":pt.getAllHeaderCells,"removeHeaderRows":pt.removeHeaderRows,"addFooterRows":pt.addFooterRows,"getFooterCell":pt.getFooterCell,
"getAllFooterCells":pt.getAllFooterCells,"removeFooterRows":pt.removeFooterRows,"sort":pt.sort,"setSortLogic":pt.setSortLogic,"getColumnIndex":pt.getColumnIndex,"getRowIndex":pt.getRowIndex,"toCellIndex":pt.toCellIndex,"toIndexPoint":pt.toIndexPoint,"getColumnLeft":pt.getColumnLeft,"getRowTop":pt.getRowTop,"getCellPosition":pt.getCellPosition,"setContent":pt.setContent,"setHeaderContent":pt.setHeaderContent,"setFooterContent":pt.setFooterContent,"rebuild":pt.rebuild,"cloak":pt.cloak,"getBody":pt.getBody,
"getHeader":pt.getHeader,"getFooter":pt.getFooter};for(var key in obj)pt[key]=obj[key]})();var PerfTester=function(configObj){this._runTest=this._runTest.bind(this);this._onTesting=this._onTesting.bind(this);this._onTestCompleted=this._onTestCompleted.bind(this);this._tasks=[];this._results=[];this._defaults={"before":"","beforeEach":"","afterEach":"","after":""};this.config(configObj)};Ext.inherits(PerfTester,EventDispatcher);PerfTester.TestResult;PerfTester.TestCase;PerfTester.TestResults;PerfTester.prototype._roundLimit=5;PerfTester.prototype._roundInterval=100;PerfTester.prototype._defaults;
PerfTester.prototype._results;PerfTester.prototype._tasks;PerfTester.prototype._currentTask=null;PerfTester.prototype._completedTasks=0;PerfTester.prototype.config=function(configObj){if(!configObj)return;this.addListeners(configObj["listeners"]);var val=configObj["round"];if(typeof val==="number")this._roundLimit=val;val=configObj["roundInterval"];if(typeof val==="number")this._roundInterval=val};
PerfTester.prototype.runTest=function(testCase){if(testCase){var testContent=testCase["testContent"];var before=testCase["before"]||this._defaults["before"];var after=testCase["after"]||this._defaults["after"];var beforeEach=testCase["beforeEach"]||this._defaults["beforeEach"];var afterEach=testCase["afterEach"]||this._defaults["afterEach"];var testMethod=null;var estTime=0;try{var testLines=[];testLines.push("(function(__batchSize) { ");if(before)testLines.push(before+";");if(beforeEach){testLines.push("var __elapsedTime = 0;");
testLines.push("for(var __i = __batchSize; --__i >= 0;) {");testLines.push(beforeEach+";");testLines.push("var __begin = new Date().getTime();");testLines.push(testContent+";");testLines.push("__elapsedTime += (new Date()).getTime() - __begin;");if(afterEach)testLines.push(afterEach+";");testLines.push("}")}else{testLines.push("var __begin = new Date().getTime();");testLines.push("for(var __i = __batchSize; --__i >= 0;) {");testLines.push(testContent+";");testLines.push("}");testLines.push("var __end = new Date().getTime();")}if(after)testLines.push(after+
";");if(beforeEach)testLines.push("return __elapsedTime;})");else testLines.push("return __end - __begin;})");testMethod=eval(testLines.join("\n"));estTime=testMethod(1)}catch(err){this.dispatch("error",err);return false}testCase["testMethod"]=testMethod;testCase["estimatedTime"]=estTime;this._tasks.push(testCase);setTimeout(this._runTest,20);return true}this.dispatch("error",{"message":"No test case detected"});return false};
PerfTester.prototype.isRunningTest=function(){return this._currentTask?true:false};PerfTester.prototype.setBeforeContent=function(str){this._defaults["before"]=str||""};PerfTester.prototype.setBeforeEachContent=function(str){this._defaults["beforeEach"]=str||""};PerfTester.prototype.setAfterContent=function(str){this._defaults["after"]=str||""};PerfTester.prototype.setAfterEachContent=function(str){this._defaults["afterEach"]=str||""};PerfTester.prototype.getTestResults=function(){return this._results};
PerfTester.prototype.clearTestResults=function(){this._results.length=0};
PerfTester.prototype.createResultTable=function(results,elem){if(!results)results=this.getTestResults();var rowCount=results.length;if(elem)Dom.removeChildren(elem);var tbl=new Table(elem,5,rowCount);tbl.setHeaderContent(["#","Avg. execution time (ms)","Avg. number of execution","Speed Ratio","Test Case"]);var min=NaN,max=NaN;var minAt=0,maxAt=0;var r,avgTime,execCount;for(r=0;r<rowCount;++r){avgTime=results[r]["avgTime"];if(!(avgTime>=min)){min=avgTime;minAt=r}if(!(avgTime<=max)){max=avgTime;maxAt=
r}}for(r=0;r<rowCount;++r){var result=results[r];avgTime=result["avgTime"];execCount=result["execCount"];var speedRatio=avgTime<max?max/avgTime:1;var testContent=result["testContent"];var shorthenText=testContent.length>1E3?testContent.substr(0,1E3):testContent;tbl.getCell(0,r).textContent=r;tbl.getCell(1,r).textContent=+avgTime.toFixed(8);tbl.getCell(2,r).textContent=execCount;tbl.getCell(3,r).textContent=+speedRatio.toFixed(2)+"x";tbl.getCell(4,r).textContent=shorthenText}if(minAt!==maxAt){tbl.getRow(maxAt).className=
"slowest";tbl.getRow(minAt).className="fastest"}return tbl};
PerfTester.prototype._runTest=function(){if(this._currentTask)return;if(!this._tasks.length){if(this._completedTasks){this.dispatch("testCompleted",{});this._completedTasks=0}return}this._currentTask=this._tasks.shift();var estTime=this._currentTask["estimatedTime"]||1;this._currentTask["result"]={"round":0,"execCount":0,"elapsedTime":0,"testContent":this._currentTask.testContent,"batchSize":Math.ceil(this._roundInterval/10/estTime)};this.dispatch("testStarted",{});setTimeout(this._onTesting,20)};
PerfTester.prototype._onTesting=function(){var execCount=0;var elapsedTime=0;var roundInterval=this._roundInterval;var testMethod=this._currentTask["testMethod"];var result=this._currentTask["result"];var batchSize=result["batchSize"];while(elapsedTime<roundInterval){var diff=testMethod(batchSize);elapsedTime+=diff;execCount+=batchSize;if(diff<=1)batchSize++;else if(batchSize>1&&diff>roundInterval)batchSize--}result["execCount"]+=execCount;result["elapsedTime"]+=elapsedTime;result["batchSize"]=batchSize;
result["round"]++;if(result["round"]<this._roundLimit){this.dispatch("progress",result);setTimeout(this._onTesting,20)}else{result["avgTime"]=result["elapsedTime"]/result["execCount"];this._results.push(result);this._onTestCompleted()}};PerfTester.prototype._onTestCompleted=function(){++this._completedTasks;this.dispatch("caseCompleted",this._currentTask);this._currentTask=null;this._runTest()};window["PerfTester"]=PerfTester;
(function(){var pt=PerfTester.prototype;var obj={"config":pt.config,"runTest":pt.runTest,"isRunningTest":pt.isRunningTest,"setBeforeContent":pt.setBeforeContent,"setBeforeEachContent":pt.setBeforeEachContent,"setAfterContent":pt.setAfterContent,"setAfterEachContent":pt.setAfterEachContent,"getTestResults":pt.getTestResults,"clearTestResults":pt.clearTestResults,"createResultTable":pt.createResultTable};for(var key in obj)pt[key]=obj[key]})();
